### ISSUE TITLE
[state-storage] Add KMS permission to documentation

### ISSUE THREAD

**Issue by kernwig** [onicagroup/sailplane#60]
If reading or writing secure SMS parameters, additional permissions are needed.

```
  - Effect: Allow
    Action:
      - kms:Decrypt
      - kms:Encrypt
    Resource: "arn:aws:kms:${opt:region}:*:alias/aws/ssm"
    Condition:
      StringEquals:
        "kms:EncryptionContext:PARAMETER_ARN": "arn:aws:ssm:${opt:region}:*:parameter${self:provider.environment.STATE_STORAGE_PREFIX}/*"
```

Update this in the example @ https://docs.onica.com/projects/sailplane/en/latest/state_storage.html
